### ISSUE TITLE
Add ipython notebook demonstrating throughput curves. 

### ISSUE THREAD

**Issue by rhiannonlynne** [lsst/throughputs#1]
I want to replace the documentation here 
http://ssg.astro.washington.edu/elsst/magsfilters.shtml?filterinfo
with an ipython notebook that can regenerate the same plots (especially as the throughput curves are updated). The ipython notebook can generate plots that go into the repo as documentation, and also can be viewed through nbviewer (http://nbviewer.ipython.org/ + paste in github URL). 
By rerunning the ipython notebook, up to date versions of the plots can be generated as the throughput curves are updated.

**Comment by RobertLuptonTheGood** [comment]
Just to state the obvious, you only have to paste the URL to the repo, and all the notebooks in the repo are rendered in nbviewer.

**Comment by rhiannonlynne** [comment]
Exactly!

**Comment by rhiannonlynne** [comment]
The ipython notebook with the throughput curves can be viewed at http://nbviewer.ipython.org/github/lsst/throughputs/blob/Add-ipython-notebook/examples/LSST%20Throughputs%20Curves.ipynb
.. let me know if you have comments. 
(@ivezic and Chuck Claver -- can I tag people like this?)

**Comment by ivezic** [comment]
```
     Hi Lynne,
```

I am not sure if I can simply reply to your email from github, nor if Chuck is on 
that list, so I am cc-ing you both explicitly.

I just managed to run your notebook without any problem! (I do mean it: not 
just looked at the rendered version on nbviewer, but run it on my laptop, 
see the title in the attached plot!). 

On a more serious note: is the plan that now Chuck will update all the
throughput files in that github repo?  Are we going to tag a version that
I will use for the overview paper update? When can we pass this on to
Debbie Bard (who asked for up-to-date throughputs)? 

Chuck, shall we touch base about all this next Monday at 3pm when we 
meet for Peter’s sky brightness presentation? 

```
   Cheers, Zeljko 
```

**Comment by ivezic** [comment]
Zeljko and Lynne,

Yes - I the plan is for me to update the github repository to include 
the files I have been using recently for the m5 calculations and other 
analysis.

Zeljko,  yes let's touch base on Monday.

Cheers,
Chuck

> ```
>      Hi Lynne,
> ```
> 
> I am not sure if I can simply reply to your email from github, nor if 
> Chuck is on
> that list, so I am cc-ing you both explicitly.
> 
> I just managed to run your notebook without any problem! (I do mean 
> it: not
> just looked at the rendered version on nbviewer, but run it on my laptop,
> see the title in the attached plot!).
> 
> On a more serious note: is the plan that now Chuck will update all the
> throughput files in that github repo?  Are we going to tag a version that
> I will use for the overview paper update? When can we pass this on to
> Debbie Bard (who asked for up-to-date throughputs)?
> 
> Chuck, shall we touch base about all this next Monday at 3pm when we
> meet for Peter’s sky brightness presentation?
> 
> ```
>    Cheers, Zeljko
> ```
> 
> On Mar 6, 2015, at 3:14 AM, Lynne Jones <notifications@github.com

**Comment by rhiannonlynne** [comment]
Robert made a comment asking if we needed all the extra environment variables. After searching, it seems we're only using two (LSST_THROUGHPUTS_*), so I've dropped the rest. They can be 'reconstituted' by using the base directory + the subdirectory name.

**Comment by rhiannonlynne** [comment]
Updated the notebook as well. I'm going to merge the branch and close the issue.
