### ISSUE TITLE
Appropriate citation info?

### ISSUE THREAD

**Issue by djperrefort** [lsst/throughputs#13]
When writing a paper that refers to the LSST throughput data in this repository, is there a preferred method of academic attribution? Right now I have a paper draft with a footnote linking to this repository. I wasn't sure if there is a more formal reference I should point to.

**Comment by rhiannonlynne** [comment]
My apologies for not seeing this issue sooner! 
In the past, we have preferred citations along the line of the LSST simulations references suggested here - https://github.com/lsst-pst/LSSTreferences - but for use of only the LSST throughputs curves, this seems heavier weight that required. 
Using the repository is fine, although you should probably make sure to include information like the version number.
